// Code generated by mockery v2.10.2. DO NOT EDIT.

package mockqueue

import (
	queue "github.com/pustato/otus_home_work/hw12_13_14_15_calendar/internal/queue"
	mock "github.com/stretchr/testify/mock"
)

// Consumer is an autogenerated mock type for the Consumer type
type Consumer struct {
	mock.Mock
}

// Consume provides a mock function with given fields: h
func (_m *Consumer) Consume(h queue.MessageHandler) error {
	ret := _m.Called(h)

	var r0 error
	if rf, ok := ret.Get(0).(func(queue.MessageHandler) error); ok {
		r0 = rf(h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
